# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/generated_plugin_registrant.dart"
    - "**/*.mocks.dart"  # Generated mock files
    - "test/**"  # Test files
    - "scripts/**"  # Build/setup scripts
    # Excluded due to missing helper methods - file appears truncated/incomplete
    - "lib/features/contests/widgets/unified_contest_card.dart"

  errors:
    # Ignore info-level analyzer hints that generate high volume of warnings
    unintended_html_in_doc_comment: ignore  # Doc comment angle brackets - common in Dart docs
    deprecated_member_use: ignore  # SDK deprecations - will fix during upgrades
    deprecated_member_use_from_same_package: ignore  # Internal deprecations - temporary
    use_build_context_synchronously: ignore  # Async context usage - handled by mounted checks
    unused_field: ignore  # Unused fields - may be used in future
    unused_local_variable: ignore  # Unused variables - may be used in future
    unused_element: ignore  # Unused elements - may be used in future
    dead_null_aware_expression: ignore  # Null-aware on non-null - style preference
    unused_result: ignore  # Unused return values - sometimes intentional
    library_private_types_in_public_api: ignore  # Private types in public API - Flutter pattern
    strict_top_level_inference: ignore  # Type inference - Dart handles this well
    unreachable_switch_default: ignore  # Default cases in exhaustive switches - safety preference
    dead_code: ignore  # Dead code - may be used in future
    body_might_complete_normally_nullable: ignore  # Nullable return - handled by checks
    dangling_library_doc_comments: ignore  # Doc comment placement - style preference

  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

linter:
  rules:
    # Error rules (disabled high-volume info-level rules)
    avoid_slow_async_io: false  # Info-level, async I/O sometimes needed
    cancel_subscriptions: true
    close_sinks: true
    comment_references: true
    control_flow_in_finally: true
    empty_statements: true
    hash_and_equals: true
    invariant_booleans: true
    literal_only_boolean_expressions: true
    no_adjacent_strings_in_list: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    unnecessary_statements: true
    unrelated_type_equality_checks: true
    valid_regexps: true

    # Style rules (disabled rules that generate high volume of info-level warnings)
    always_declare_return_types: true
    always_put_control_body_on_new_line: false  # Info-level, style preference
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_annotating_with_dynamic: true
    avoid_bool_literals_in_conditional_expressions: false  # Info-level, style preference
    avoid_catches_without_on_clauses: false  # Info-level, sometimes catch-all is needed
    avoid_catching_errors: false  # Info-level, sometimes needed for error recovery
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    avoid_equals_and_hash_code_on_mutable_classes: false  # Info-level, sometimes needed
    avoid_escaping_inner_quotes: true
    avoid_field_initializers_in_const_classes: false  # Info-level, sometimes default values are clearer
    avoid_function_literals_in_foreach_calls: true
    avoid_implementing_value_types: false  # Info-level, sometimes needed
    avoid_init_to_null: true
    avoid_null_checks_in_equality_operators: true
    avoid_positional_boolean_parameters: false  # Info-level, API design preference
    avoid_print: false  # Info-level, sometimes needed for debugging
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_shadowing_type_parameters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_types_as_parameter_names: false  # Info-level, parameter naming
    avoid_types_on_closure_parameters: true
    avoid_unnecessary_containers: false  # Info-level, sometimes containers are useful for structure
    avoid_unused_constructor_parameters: true
    avoid_void_async: true
    await_only_futures: true
    camel_case_extensions: true
    camel_case_types: true
    cascade_invocations: false  # Info-level, style preference
    cast_nullable_to_non_nullable: true
    constant_identifier_names: false  # Info-level, naming preference
    curly_braces_in_flow_control_structures: true
    directives_ordering: true
    empty_catches: true
    empty_constructor_bodies: true
    exhaustive_cases: true
    file_names: true
    flutter_style_todos: false  # Info-level, TODO style preference
    implementation_imports: true
    join_return_with_assignment: false  # Info-level, sometimes clearer to keep separate
    leading_newlines_in_multiline_strings: true
    library_names: true
    library_prefixes: true
    lines_longer_than_80_chars: false  # Info-level, modern displays support longer lines
    missing_whitespace_between_adjacent_strings: true
    no_default_cases: false  # Info-level, switch exhaustiveness handled by analyzer
    non_constant_identifier_names: true
    null_closures: true
    omit_local_variable_types: true
    one_member_abstracts: true
    only_throw_errors: false  # Info-level, throwing strings can be acceptable
    overridden_fields: true
    package_prefixed_library_names: true
    parameter_assignments: true
    prefer_adjacent_string_concatenation: true
    prefer_asserts_in_initializer_lists: true
    prefer_collection_literals: true
    prefer_conditional_assignment: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_equal_for_default_values: true
    prefer_expression_function_bodies: false  # Info-level, sometimes block bodies are clearer
    prefer_final_fields: true
    prefer_final_in_for_each: true
    prefer_final_locals: false  # Info-level, style preference
    prefer_for_elements_to_map_fromIterable: true
    prefer_foreach: false  # Info-level, for-loops can be clearer
    prefer_function_declarations_over_variables: true
    prefer_generic_function_type_aliases: true
    prefer_if_elements_to_conditional_expressions: true
    prefer_if_null_operators: true
    prefer_initializing_formals: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    prefer_is_not_operator: true
    prefer_iterable_whereType: true
    prefer_null_aware_operators: true
    prefer_relative_imports: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    prefer_typing_uninitialized_variables: true
    provide_deprecation_message: true
    public_member_api_docs: false  # Info-level, not required for app code
    recursive_getters: true
    require_trailing_commas: false  # Info-level, style preference
    sized_box_for_whitespace: true
    slash_for_doc_comments: true
    sort_child_properties_last: false  # Info-level, style preference
    sort_constructors_first: false  # Info-level, style preference
    sort_pub_dependencies: false  # Info-level, package ordering is semantic not alphabetic
    sort_unnamed_constructors_first: true
    type_annotate_public_apis: false  # Info-level, Dart has good type inference
    unawaited_futures: false  # Info-level, fire-and-forget sometimes intentional
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: false  # Info-level, sometimes lambdas are clearer
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_raw_strings: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    unnecessary_this: true
    use_full_hex_values_for_flutter_colors: true
    use_function_type_syntax_for_parameters: true
    use_rethrow_when_possible: true
    use_setters_to_change_properties: false  # Info-level, methods can be clearer
    use_string_buffers: false  # Info-level, concatenation is fine for small strings
    use_to_and_as_if_applicable: true
    void_checks: true

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
