// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLbFJfYQ96GG81-1vuLLq1lGCXDOV-sag',
    appId: '1:49516074337:web:456b9e8a0454347eaba120',
    messagingSenderId: '49516074337',
    projectId: 'sweep-feed',
    authDomain: 'sweep-feed.firebaseapp.com',
    storageBucket: 'sweep-feed.firebasestorage.app',
    measurementId: 'G-S30417FD6P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl4OMnkVE7qiBE1v-zD5TQgiAdbZYF2WA',
    appId: '1:49516074337:android:3e8d63cda57abc78aba120',
    messagingSenderId: '49516074337',
    projectId: 'sweep-feed',
    storageBucket: 'sweep-feed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCh4U6tSxeaVgjAFXX_0ePL778IvEK8smk',
    appId: '1:49516074337:ios:a449e44e707d99adaba120',
    messagingSenderId: '49516074337',
    projectId: 'sweep-feed',
    storageBucket: 'sweep-feed.firebasestorage.app',
    androidClientId: '49516074337-4jv99vsl36e15uk7l9sbagbuib3q94gs.apps.googleusercontent.com',
    iosClientId: '49516074337-iu16fcq60at3q9iudv1o87sbb8d4u30t.apps.googleusercontent.com',
    iosBundleId: 'com.sweepfeed.app',
  );
}
